package mathtext

import "strings"

var displayTextCommandReplacer = strings.NewReplacer(
	`\\alpha`, "α",
	`\\beta`, "β",
	`\\gamma`, "γ",
	`\\delta`, "δ",
	`\\epsilon`, "ε",
	`\\eta`, "η",
	`\\theta`, "θ",
	`\\lambda`, "λ",
	`\\mu`, "μ",
	`\\nu`, "ν",
	`\\pi`, "π",
	`\\rho`, "ρ",
	`\\sigma`, "σ",
	`\\tau`, "τ",
	`\\phi`, "φ",
	`\\chi`, "χ",
	`\\psi`, "ψ",
	`\\omega`, "ω",
	`\\Gamma`, "Γ",
	`\\Delta`, "Δ",
	`\\Theta`, "Θ",
	`\\Lambda`, "Λ",
	`\\Pi`, "Π",
	`\\Sigma`, "Σ",
	`\\Phi`, "Φ",
	`\\Psi`, "Ψ",
	`\\Omega`, "Ω",
	`\\pm`, "±",
	`\\mp`, "∓",
	`\\times`, "×",
	`\\cdot`, "·",
	`\\deg`, "°",
	`\\le`, "≤",
	`\\ge`, "≥",
	`\\neq`, "≠",
	`\\approx`, "≈",
	`\\infty`, "∞",
	`\\partial`, "∂",
	`\\nabla`, "∇",
	`\\rightarrow`, "→",
	`\\leftarrow`, "←",
	`\\leftrightarrow`, "↔",
)

var mathTextCommandMap = map[string]string{
	"alpha":          "α",
	"beta":           "β",
	"gamma":          "γ",
	"delta":          "δ",
	"epsilon":        "ε",
	"varepsilon":     "ϵ",
	"eta":            "η",
	"theta":          "θ",
	"vartheta":       "ϑ",
	"lambda":         "λ",
	"mu":             "μ",
	"nu":             "ν",
	"pi":             "π",
	"rho":            "ρ",
	"sigma":          "σ",
	"tau":            "τ",
	"phi":            "φ",
	"varphi":         "φ",
	"chi":            "χ",
	"psi":            "ψ",
	"omega":          "ω",
	"Gamma":          "Γ",
	"Delta":          "Δ",
	"Theta":          "Θ",
	"Lambda":         "Λ",
	"Pi":             "Π",
	"Sigma":          "Σ",
	"Phi":            "Φ",
	"Psi":            "Ψ",
	"Omega":          "Ω",
	"pm":             "±",
	"mp":             "∓",
	"times":          "×",
	"cdot":           "·",
	"div":            "÷",
	"ast":            "∗",
	"circ":           "∘",
	"bullet":         "•",
	"deg":            "°",
	"le":             "≤",
	"leq":            "≤",
	"ge":             "≥",
	"geq":            "≥",
	"ne":             "≠",
	"neq":            "≠",
	"approx":         "≈",
	"equiv":          "≡",
	"propto":         "∝",
	"sim":            "∼",
	"infty":          "∞",
	"partial":        "∂",
	"nabla":          "∇",
	"ell":            "ℓ",
	"sum":            "∑",
	"prod":           "∏",
	"int":            "∫",
	"oint":           "∮",
	"forall":         "∀",
	"exists":         "∃",
	"in":             "∈",
	"notin":          "∉",
	"subset":         "⊂",
	"subseteq":       "⊆",
	"supset":         "⊃",
	"supseteq":       "⊇",
	"cup":            "∪",
	"cap":            "∩",
	"land":           "∧",
	"lor":            "∨",
	"oplus":          "⊕",
	"otimes":         "⊗",
	"to":             "→",
	"rightarrow":     "→",
	"leftarrow":      "←",
	"leftrightarrow": "↔",
	"ldots":          "…",
}

var mathTextOperatorMap = map[string]string{
	"arccos": "arccos",
	"arcsin": "arcsin",
	"arctan": "arctan",
	"arg":    "arg",
	"cos":    "cos",
	"cosh":   "cosh",
	"cot":    "cot",
	"coth":   "coth",
	"csc":    "csc",
	"deg":    "deg",
	"det":    "det",
	"dim":    "dim",
	"exp":    "exp",
	"gcd":    "gcd",
	"hom":    "hom",
	"inf":    "inf",
	"ker":    "ker",
	"lg":     "lg",
	"lim":    "lim",
	"liminf": "lim inf",
	"limsup": "lim sup",
	"ln":     "ln",
	"log":    "log",
	"max":    "max",
	"min":    "min",
	"Pr":     "Pr",
	"sec":    "sec",
	"sin":    "sin",
	"sinh":   "sinh",
	"sup":    "sup",
	"tan":    "tan",
	"tanh":   "tanh",
}

// mathTextAccentMarks drives the plain-text (non-layout) fallback: each accent
// is approximated by appending a Unicode combining mark to the nucleus. The
// layout parser instead builds centred separate-glyph Accent nodes (accent.go).
var mathTextAccentMarks = map[string]rune{
	"bar":            '̅',
	"overline":       '̅',
	"hat":            '̂',
	"widehat":        '̂',
	"tilde":          '̃',
	"widetilde":      '̃',
	"widebar":        '̅',
	"vec":            '⃗',
	"dot":            '̇',
	"ddot":           '̈',
	"dddot":          '⃛',
	"ddddot":         '⃜',
	"breve":          '̆',
	"grave":          '̀',
	"acute":          '́',
	"mathring":       '̊',
	"overrightarrow": '⃗',
	"overleftarrow":  '⃖',
}

var mathTextPassthroughCommands = map[string]struct{}{
	"mathrm":       {},
	"mathit":       {},
	"mathdefault":  {},
	"mathbf":       {},
	"mathsf":       {},
	"mathtt":       {},
	"text":         {},
	"operatorname": {},
}

var mathTextEmptyCommands = map[string]struct{}{
	"left":              {},
	"middle":            {},
	"right":             {},
	"limits":            {},
	"nolimits":          {},
	"displaystyle":      {},
	"textstyle":         {},
	"scriptstyle":       {},
	"scriptscriptstyle": {},
}

var mathTextSpacingCommands = map[string]string{
	",":             " ",
	":":             " ",
	";":             " ",
	"thinspace":     " ",
	"medspace":      " ",
	"thickspace":    " ",
	"negthinspace":  "",
	"negmedspace":   "",
	"negthickspace": "",
	"enspace":       " ",
	"enskip":        " ",
	"quad":          "  ",
	"qquad":         "    ",
}

var mathTextDelimiterCommands = map[string]string{
	"langle": "⟨",
	"rangle": "⟩",
	"lbrace": "{",
	"rbrace": "}",
	"lvert":  "|",
	"rvert":  "|",
	"lVert":  "‖",
	"rVert":  "‖",
	"lfloor": "⌊",
	"rfloor": "⌋",
	"lceil":  "⌈",
	"rceil":  "⌉",
}

var superscriptRunes = map[rune]string{
	'0': "⁰",
	'1': "¹",
	'2': "²",
	'3': "³",
	'4': "⁴",
	'5': "⁵",
	'6': "⁶",
	'7': "⁷",
	'8': "⁸",
	'9': "⁹",
	'+': "⁺",
	'-': "⁻",
	'=': "⁼",
	'(': "⁽",
	')': "⁾",
	'n': "ⁿ",
	'i': "ⁱ",
	'a': "ᵃ",
	'b': "ᵇ",
	'c': "ᶜ",
	'd': "ᵈ",
	'e': "ᵉ",
	'f': "ᶠ",
	'g': "ᵍ",
	'h': "ʰ",
	'j': "ʲ",
	'k': "ᵏ",
	'l': "ˡ",
	'm': "ᵐ",
	'o': "ᵒ",
	'p': "ᵖ",
	'r': "ʳ",
	's': "ˢ",
	't': "ᵗ",
	'u': "ᵘ",
	'v': "ᵛ",
	'w': "ʷ",
	'x': "ˣ",
	'y': "ʸ",
	'z': "ᶻ",
}

var subscriptRunes = map[rune]string{
	'0': "₀",
	'1': "₁",
	'2': "₂",
	'3': "₃",
	'4': "₄",
	'5': "₅",
	'6': "₆",
	'7': "₇",
	'8': "₈",
	'9': "₉",
	'+': "₊",
	'-': "₋",
	'=': "₌",
	'(': "₍",
	')': "₎",
	'a': "ₐ",
	'e': "ₑ",
	'h': "ₕ",
	'i': "ᵢ",
	'j': "ⱼ",
	'k': "ₖ",
	'l': "ₗ",
	'm': "ₘ",
	'n': "ₙ",
	'o': "ₒ",
	'p': "ₚ",
	'r': "ᵣ",
	's': "ₛ",
	't': "ₜ",
	'u': "ᵤ",
	'v': "ᵥ",
	'x': "ₓ",
	'β': "ᵦ",
	'γ': "ᵧ",
	'ρ': "ᵨ",
	'φ': "ᵩ",
	'χ': "ᵪ",
}
